# Site settings
title: Kwality Hardwares
description: "Kwality Industrial Tools & Hardware Portfolio"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the name of your domain
logo_url: svg/min/logo.svg

# Hero
hero: 
    hero_img: hero.jpg
    hero_title: Kwality Industrial Tools & Hardwares
    hero_description: Our company is a renowned trader, dealer and supplier of products such as Gas Welding Rod, Spring Washer, Drill Bit, Drilling Machine and many more. We offer our products at low prices in the market.

# Contact form
api_token: # Enter API token here

# Contact info
contact:
    phone: +91 8043042360
    email: p.balakumar@hotmail.com
    address: Plot No. 6, Mahalakshmi Street, M.C. Nagar, <br> Chennai - 600064, Tamil Nadu, India

# Opening hours
monday_friday: 9:00 – 20:00
saturday: 10:00 – 13:00
sunday: Holiday

# Testimonials
testimonials:
    testimonials_img: parallax.jpg

# Map
map:
    zoom: 17
    address: Von schroeders 273, Viña del mar, Chile
    address_details: svg/min/logo.svg

# Social settings
facebook: http://facebook.com
twitter: http://twitter.com
instagram: http://instagram.com
youtube: http://youtube.com
skype: skype:kwalityhardwares
feed: yes

# Footer
copyright: © 2016 Kwality Industrial Tools & Hardwares - All rights reserved

# Build settings
markdown: kramdown

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

# Theme Settings
analytics: 
google_verification:
